### ISSUE TITLE
bbox's shape is bigger than windowsize

### ISSUE THREAD

**Issue by laocan** [ultralytics/yolov5#1714]
## ❔Question
I've set windowsize:(640,640)
but get the pred result xyxy: [-5.00000e+00,  3.17500e+01,  6.41500e+02,  6.44000e+02] ,
the coord result is out of the range of [0, 640] at position: xyxy[0,2,3]= [-5, 641.5, 644] .
obviously, the width is bigger than 640, why???

**Comment by glenn-jocher** [comment]
@laocan good observation. Clipping is done in detect.py and test.py, but is not currently implemented in .autoshape() models.

**Comment by laocan** [comment]
Got it. I find it in utils.general.scale_coords.
thx @glenn-jocher

**Comment by glenn-jocher** [comment]
@laocan yes, we may want to add it to the autoshape postprocessing step here.
https://github.com/ultralytics/yolov5/blob/6bd5e8bca74afe497178181661648218dfbc8d5a/models/common.py#L183-L186

Though its possible scale_coords() may include this functionality...?

**Comment by glenn-jocher** [comment]
Yes, it looks like scale_coords() should already be clipping on L171, though its possible it is clipping to the padded image bounds rather than the native image size. Perhaps you could investigate here.
https://github.com/ultralytics/yolov5/blob/6bd5e8bca74afe497178181661648218dfbc8d5a/utils/general.py#L159-L172

**Comment by glenn-jocher** [comment]
@laocan I tested myself just now and everything appears working correctly, coordinates clip to image bounds as expected. Can you supply exact code to reproduce your example please?

**Comment by laocan** [comment]
Thx for the help of @glenn-jocher .
I didn't use utils.general.scale_coords so that error occured
I've fixed it during postprocessing following the clip_coords way.
thx again ^_^

**Comment by glenn-jocher** [comment]
@laocan I'm still not understanding the workflow that you used to allow this larger output box than image size. Can you please provide a reproducible example if this was done using the default code (and not part of custom code?). Thank you.

EDIT: If this is happening in master (without changes) then this is a bug and something that needs to be fixed.
