### ISSUE TITLE
The train.py script prints tensor then quits

### ISSUE THREAD

**Issue by cubrink** [ultralytics/yolov5#3284]
## 🐛 Bug

When using `train.py` a tensor is printed to screen and then the script ends. No training occurs.

## To Reproduce (REQUIRED)

Input:
```
cd <path_to_save_to>/
git clone https://github.com/ultralytics/yolov5.git    # At time of writing: commit 683cefead4b9f2a8d062f953a912e46e456ed6ad
cd yolov5

conda create --name yolov5-bug          # Create new environment
conda activate yolov5-bug
conda install python==3.8.*             # Base python install
conda install -c pytorch torchvision    # Install pytorch from official conda channel. 
                                        # This auto configures GPU support and has worked for me in the past
                                        # Currently this installs torchvision==0.9.1, pytorch==1.8.1, cudatoolkit==10.2.89
conda install cudnn                     # More GPU setup

pip install -r requirements.txt         # Get remaining dependencies


# Download yolov5m.pt from https://github.com/ultralytics/yolov5/releases
# Place yolov5m.pt in yolov5/weights

# Download coco128
# Place at ../coco128 

python train.py --weights weights/yolov5m.pt \
                --data data/coco128.yaml \
                --cfg models/yolov5m.yaml \
                --name yolov5-bug
```

Output:
The training script starts normally and sits idle briefly. Then a tensor is printed to screen and the script ends.
Inititally
![start](https://user-images.githubusercontent.com/25831062/119194788-3933b100-ba49-11eb-9eac-090bcc7f3706.png)
Then,
![output](https://user-images.githubusercontent.com/25831062/119194852-523c6200-ba49-11eb-8c8d-945b723a7469.png)

After the script has stopped `runs/train/yolov5-bug` is only partially filled. I'm unsure if this is relevant.
`runs/train/yolov5-bug` contents:
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         5/21/2021   3:11 PM                weights
------         5/21/2021   3:11 PM           5533 events.out.tfevents...
------         5/21/2021   3:11 PM            356 hyp.yaml
------         5/21/2021   3:11 PM         457560 labels.jpg
------         5/21/2021   3:11 PM         349727 labels_correlogram.jpg
------         5/21/2021   3:11 PM            672 opt.yaml
------         5/21/2021   3:11 PM         365691 train_batch0.jpg
```
(`.tfevents` filename partially redacted for privacy reasons)

## Expected behavior

Regular training on the coco128 test dataset.

## Environment

 - OS: Ubuntu 18.04.5 LTS
 - GPU 4x RTX 2080 Ti

## Additional context

I've used older versions of YoloV5 before without issue. I recently decided to try updating before I ran into this issue.
I will not be able to access this machine again until Monday.

**Comment by cubrink** [comment]
I did some further testing by checking out different commits. The first commit that produced the bug is [this one](https://github.com/ultralytics/yolov5/commit/b7cd1f540d5815b0a1cf2e23ce82a5fdb8f6b525).

**Comment by glenn-jocher** [comment]
@cubrink thanks for the bug report. Conda environments may produce problems sometimes, I would recommend you try one of our verified environments above, including the Docker image.

A few comments about your example:
- YOLOv5 models are autodownloaded on first request, so you can eliminate this step in your workflow.
- COCO128 is autodownloaded on first request, so you can eliminate this step in your workflow
- Multi-GPU training should be done using DDP commands for best results. See Multi-GPU training tutorial below.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by yogaaltariz** [comment]
![image](https://user-images.githubusercontent.com/43367856/119263200-464ace80-bc08-11eb-9817-164d00dd1258.png)

happened to me too with the latest update yolov5. I have create new virtual env and run pip install -r requirements.txt but still not solve the problem

**Comment by cubrink** [comment]
@glenn-jocher, thank you for the advice, I'm aware of the auto-downloading features but the firewall on the machine in question blocks the download.

I've since ran the script in the Docker container using DDP and have ran into similar issues.

Edit: I can again confirm that the first commit to break the training script is [this one](https://github.com/ultralytics/yolov5/commit/b7cd1f540d5815b0a1cf2e23ce82a5fdb8f6b525). This was the same commit that broke `train.py` in my initial bug report.

It looks like the line that breaks `train.py` is:
```python
if tb_writer:
    tb_writer.add_graph(torch.jit.trace(model, imgs, strict=False), [])  # add model graph
```
On [line 333](https://github.com/ultralytics/yolov5/blob/master/train.py#L333) of `train.py`. I was able to fix `train.py` by commenting out the previously mentioned lines.

### The bugs: 
Within docker, using DDP: The training hangs indefinitely shortly after starting.
Within docker, without DDP: The original error occurs. (Tensor is printed then script exits)

## Environment

 - OS: Ubuntu 18.04.5 LTS
 - GPU: 4x RTX 2080 Ti
 - NVIDIA Drivers: 465.19.01
 - Docker version: 19.03.13

## To Reproduce

Basic setup
```
# Volume added due to autodownload being blocked due to firewall settings
# On a different machine the volume would not be needed.
# The data is from official sources so they should work without issue.

sudo docker --rm --ipc=host --gpus all -it -v <my_local_path>/yolov5_resources ultralytics/yolov5:latest

# (Due to personal firewall settings, copy weights into ./weights and dataset into ../coco128)
```

(At the time of writing the commit from ultralytics/yolov5:latest is `61ea23c`)

### Test with DDP:
```
python -m torch.distributed.launch \
    --nproc_per_node 4 \
    train.py \
    --weights weights/yolov5m.pt \
    --cfg models/yolov5m.yaml \
    --data data/coco128.yaml \
    --device 0,1,2,3
```
Result: Training hangs after 2 batches. I've let this sit for about 10 minutes without progress.
![DDP](https://user-images.githubusercontent.com/25831062/119395306-ee0fdd00-bc98-11eb-9d94-9a141b7f9ecf.png)
(Note the warning that is raised before hanging: `UserWarning: The input to trace is already a ScriptModule, tracing it is a no-op. Returning the object as it.`)


### Test *without* DDP:

```
python train.py \
    --weights weights/yolov5m.pt \
    --cfg models/yolov5m.yaml \
    --data data/coco128.yaml \
    --device 0,1,2,3
```
![noDDP](https://user-images.githubusercontent.com/25831062/119395392-0d0e6f00-bc99-11eb-8623-4fdcd248e6aa.png)

Result: Tensor is printed by `train.py` then then the script exits. (This is the same bug that was originally reported.)



# Expected Behavior

Regular training on the coco128 datatset.

**Comment by adrigrillo** [comment]
I have also encountered with this error training with my own dataset. Just to add some information about the problem, the stack trace before printing the full tensor is:

```python
Traceback (most recent call last):
  File "train.py", line 591, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 374, in train
    tb_writer.add_graph(torch.jit.trace(model, imgs, strict=False), [])  # add model graph
  File "/home/uas/anaconda3/envs/yolo-boats/lib/python3.8/site-packages/torch/jit/_trace.py", line 733, in trace
    return trace_module(
  File "/home/uas/anaconda3/envs/yolo-boats/lib/python3.8/site-packages/torch/jit/_trace.py", line 934, in trace_module
    module._c._create_method_from_trace(
  File "/home/uas/anaconda3/envs/yolo-boats/lib/python3.8/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/uas/anaconda3/envs/yolo-boats/lib/python3.8/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/uas/anaconda3/envs/yolo-boats/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 162, in forward
    return self.gather(outputs, self.output_device)
  File "/home/uas/anaconda3/envs/yolo-boats/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 174, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/uas/anaconda3/envs/yolo-boats/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/home/uas/anaconda3/envs/yolo-boats/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/uas/anaconda3/envs/yolo-boats/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
Tensor:
[...]
```

Additionally, as @cubrink mentioned, commenting the line out the script runs correctly.

**Comment by glenn-jocher** [comment]
Thanks guys. This must be related to a recent PR https://github.com/ultralytics/yolov5/pull/3236 that re-added the TensorBoard graph for interactive model architecture viewing in TensorBoard. It seems to be failing in some environments as in your examples above though. I'll take a look at this today. Worst case scenario we can drop it into a try: except statement.

@adrigrillo your error in particular seems to imply that a model with gradients might be causing the issue, or perhaps the nn/parallel lines are implying that only **DP or DDP models in particular are causing the error** ?

![image](https://user-images.githubusercontent.com/26833433/119465445-f4a75e80-bd43-11eb-922c-b99669b9e5f1.png)

**Comment by adrigrillo** [comment]
Now that you comment that, the problem could be produced due to the use of **DP mode** which I was not intending to use in reality. I forgot to specify the GPU to use, as I wanted to use single GPU training, and I guess that, by default, if two GPUs are available and no GPU flag specified the training will use both in DP mode.

Anyways, commenting the line makes it work in **DP mode** and with one GPU also works. Therefore, the problem may be related to the multi-gpu training and not with the gradient message.

**Comment by glenn-jocher** [comment]
@adrigrillo ok thanks, that makes sense then. It's likely that the graph/script functions were just never intended for use with DP/DDP. I think we can use the same `if is_parallel()` statement used elsewhere in these cases:
https://github.com/ultralytics/yolov5/blob/407dc5008e47b1aad5ce69f0c91b4f1ec321dd7f/train.py#L393

**Comment by glenn-jocher** [comment]
@adrigrillo @cubrink good news 😃! Your original issue may now be fixed ✅ in PR #3325. This PR de-parallelizes the model before passing it to the TensorBoard add_graph() function. This should resolve the original issue if it was only observed in  multi-GPU trainings. There is a userwarning currently when the graph is saved, but this is expected and should not cause any problems (`UserWarning: The input to trace is already a ScriptModule, tracing it is a no-op. Returning the object as it.`) To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by shufanwu** [comment]
@glenn-jocher Thanks for your great work, but I found the problem mentioned in https://github.com/ultralytics/yolov5/issues/3284#issuecomment-847270860 still existed.
when I use Docker to run the code with DDP, the training hangs indefinitely.

**Comment by glenn-jocher** [comment]
@shufanwu hi thanks for the feedback. Can you confirm you are seeing this error in the latest Docker image? You can pull the latest image using the command below. 

- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by kanybekasanbekov** [comment]
> @glenn-jocher Thanks for your great work, but I found the problem mentioned in [#3284 (comment)](https://github.com/ultralytics/yolov5/issues/3284#issuecomment-847270860) still existed.
> when I use Docker to run the code with DDP, the training hangs indefinitely.

https://github.com/ultralytics/yolov5/pull/3325 solved for me

**Comment by kanybekasanbekov** [comment]
> > @glenn-jocher Thanks for your great work, but I found the problem mentioned in [#3284 (comment)](https://github.com/ultralytics/yolov5/issues/3284#issuecomment-847270860) still existed.
> > when I use Docker to run the code with DDP, the training hangs indefinitely.
> 
> #3325 solved for me

In addition, [`develop`](https://github.com/ultralytics/yolov5/tree/develop)(default) branch still has this issue, whereas [`master`](https://github.com/ultralytics/yolov5/tree/master) branch was fixed.

**Comment by glenn-jocher** [comment]
@kanybekasanbekov @SkalskiP yes as you noticed we have a new `develop` branch. The idea is to adopt a more best practices workflow where we mostly update the develop branch and periodically merge to master on a new patch release.
`master` < `develop` < `feature`

Though bug fixes will take a different route:
`master` < `fix`
