### ISSUE TITLE
TypeError: must be real number, not str with evolve

### ISSUE THREAD

**Issue by gizemtanriver** [ultralytics/yolov5#566]
Hi, thanks for this amazing repo first of all!

I am working with the v2.0 release of the repo and so far I got quite promising results on my custom dataset. I tried to use --evolve today but I am getting a TypeError from the print_mutation function in utils.py at the end of the first run. It seems to be related to 'SGD' in hyp dictionary - which is a string. I see that the optimizer parameter was added to the dict in v2.0 so I guess this wasn't an issue in the previous release.

Input:
```
!python yolov5/train.py --img 512 --batch 16 --epochs 100 --yolov5/data/custom_data.yaml \
    --cfg yolov5/models/custom_yolov5s.yaml \
    --weights yolov5/weights/yolov5s.pt --cache --evolve
```

Output:
```
Traceback (most recent call last):
  File "yolov5/train.py", line 516, in <module>
    print_mutation(hyp, results, opt.bucket)
  File "/content/drive/.shortcut-targets-by-id/1hQ281-8ogL2dJzHbXZSWEYDIYei6RRbe/YOLOv5/yolov5/utils/utils.py", line 830, in print_mutation
    b = '%10.3g' * len(hyp) % tuple(hyp.values())  # hyperparam values
TypeError: must be real number, not str
```

**Comment by glenn-jocher** [comment]
@gizemtanriver hi, thank you for the bug report. Yes you are correct, --evolve is currently out of order due to recent PRs. It's on a long list of TODOs. I can not give you an ETA. In the meantime it's inoperable.

**Comment by glenn-jocher** [comment]
@gizemtanriver this bug should be fixed now. Let me know if you find otherwise.

**Comment by weizhou1001** [comment]
Hi, I'm on master branch with commit 9cf80b7. I'm still getting this error 
`10 epochs completed in 0.248 hours.
Results saved to runs/evolve/exp
Traceback (most recent call last):
  File "train.py", line 642, in <module>
    main(opt)
  File "train.py", line 622, in main
    print_mutation(results, hyp.copy(), save_dir, opt.bucket)
  File "/home/wzhou/src/yolov5/utils/general.py", line 804, in print_mutation
    f.write(s + ('%20.5g,' * n % vals).rstrip(',') + '\n')
TypeError: must be real number, not list
`
Any ideas what would be the problem?

**Comment by glenn-jocher** [comment]
@weizhou1001 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. --evolve works correctly, I just tested now:

```bash
!python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --evolve 5
```
![Screenshot 2022-02-10 at 13 17 13](https://user-images.githubusercontent.com/26833433/153407358-dce1acdf-bbeb-4367-83f3-5e3e77800688.png)


 We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@weizhou1001 good news 😃! A related evolution issue may now be fixed ✅ in PR #6604. This bug fixes `hyp_evolve.yaml`, which was showing the last generation result rather than the best generation.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
