### ISSUE TITLE
Error in convert model from pt to tflite

### ISSUE THREAD

**Issue by qiujianchen** [ultralytics/yolov5#6204]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I use YOLOv5n.pt to train my own datasets and want to convert pytorch model to .tflite with INT8 quantization. However, I failed. So I want to ask solutions. Thank you!
(By the way, if without INT8 quantization, I can convert it successfully.)

Command:
python export.py --data data/my_datasets_4.yaml --weights runs/train/exp/weights/best.pt --imgsz 256 320 --simplify --include tflite --batch-size 1 --int8

Error:
TensorFlow Lite: export failure: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'

Environment:
Tensorflow==2.4.0
Pytorch==1.7.1(gpu)
python==3.8

**Comment by glenn-jocher** [comment]
@qiujianchen I don't recognize this error, but just FYI --simplify does not apply to TFLite exports, and a recent bug with --int8 was resolved today in #6216

**Comment by HunarAA** [comment]
@qiujianchen have you found any solution for your problem? I have used your way for converting best.pt to tflite but still not working in my flutter app

**Comment by zldrobit** [comment]
@HunarAA You could check your converted TFLite model with `python detect.py --weights {the tflite model}.tflite --data {your image directory}`. What's the version of YOLOv5 you used to export the model? Plz use the latest `v6.1` version for exporting.

**Comment by HunarAA** [comment]
I have checked it with my webcam and it works fine. But with the flutter app it closes the app directly while the app works with YOLOv2 tflite.

Have you the command for converting YOLOv5 to tflite using v6.1?

**Comment by zldrobit** [comment]
Yes, plz see https://github.com/ultralytics/yolov5/pull/1127#issue-719902540.

**Comment by HunarAA** [comment]
error in "--cfg". I have my own models/dataset.yaml because I trained my own yolov5m.

the error: export.py: error: unrecognized arguments: --cfg models/dataset.yaml

**Comment by HunarAA** [comment]
error in "--cfg". I have my own models/dataset.yaml because I trained

**Comment by zldrobit** [comment]
Sorry for not updating https://github.com/ultralytics/yolov5/pull/1127#issue-719902540. There is no need for a `--cfg` option, and the config yaml is stored in a model weight now. Plz just ignore that argument and try again.

**Comment by glenn-jocher** [comment]
@zldrobit Apologies for the confusion. The recent changes eliminate the need for a `--cfg` argument. The config yaml is now stored within the model weight. Please disregard the `--cfg` option and reattempt the conversion. Let me know how it goes!
